version: "3"
services:
  nginx:
    image: "cra-arc/performance_nginx:latest"
    build:
      context: ../
      dockerfile: docker/performance_nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    container_name: performance_nginx
    volumes:
      - /home/cra-arc-user/cra-arc.performance:/var/www/html
  web:
    image: "cra-arc/performance_php:latest"
    build:
      context: ../
      dockerfile: docker/performance_php/Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    ports:
      - "9000"
    container_name: performance_web
    depends_on:
      - mongodb
    volumes:
            - /home/cra-arc-user/cra-arc.performance/js:/var/www/html/js
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
